name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_CLIFF_0CEEF0A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "api"
          output_location: ""
        env:
          PG_HOST         : ${{ secrets.PG_HOST }}
          PG_PORT         : ${{ secrets.PG_PORT }}
          PG_DATABASE     : ${{ secrets.PG_DATABASE }}
          PG_USER         : ${{ secrets.PG_USER }}
          PG_PASSWORD     : ${{ secrets.PG_PASSWORD }}
          PG_SSL          : ${{ secrets.PG_SSL }}
          AZURE_STORAGE_ACCOUNT   : ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY       : ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_UPLOAD_CONTAINER  : ${{ secrets.AZURE_UPLOAD_CONTAINER }}
          AZURE_RESULTS_CONTAINER : ${{ secrets.AZURE_RESULTS_CONTAINER }}
          PA_EMAIL_SEND   : ${{ secrets.PA_EMAIL_SEND }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_CLIFF_0CEEF0A00 }}
          action: "close"